[build]
buildCommand = "export JAVA_HOME=$(mise where java) && ./mvnw -DoutputFile=target/mvn-dependency-list.log -B -DskipTests clean dependency:list install"

[variables]
RAILPACK_JDK_VERSION = "17"
